### ISSUE TITLE
Windows Mixed Reality Support? 

### ISSUE THREAD

**Issue by ChuckMCCluck** [yonderbread/ame-scripts#1]
Where would someone start looking to modify these scripts to allow for Windows Mixed Reality support? The AME scripts seem to remove the Windows Mixed Reality Portal and access to any of the Mixed Reality settings if you install the [Mixed Reality Feature on Demand package](https://docs.microsoft.com/en-us/windows/application-management/manage-windows-mixed-reality) before running the scripts.

**Comment by yonderbread** [comment]
I'd make a copy of the scripts and [remove or comment out this line](https://github.com/yonderbread/ame-scripts/blob/2309847aed6ca12d4593fa03cc7f489b8d205c22/scripts/remove_appx_packages.bat#L15) to stop un-installation of that package.
